[2024-07-17T11:24:13.974+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-17T11:24:14.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-17T11:18:00+00:00 [queued]>
[2024-07-17T11:24:14.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-17T11:18:00+00:00 [queued]>
[2024-07-17T11:24:14.660+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-17T11:24:14.677+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_battery_data_task> on 2024-07-17 11:18:00+00:00
[2024-07-17T11:24:14.841+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=117) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-17T11:24:14.849+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'computer_data', 'insert_battery_data_task', 'scheduled__2024-07-17T11:18:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/collect_to_postgre_dag.py', '--cfg-path', '/tmp/tmpd1dt_8yi']
[2024-07-17T11:24:14.886+0000] {standard_task_runner.py:63} INFO - Started process 121 to run task
[2024-07-17T11:24:14.886+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask insert_battery_data_task
[2024-07-17T11:24:15.162+0000] {task_command.py:426} INFO - Running <TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-17T11:18:00+00:00 [running]> on host 894f80df4663
[2024-07-17T11:24:16.068+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='computer_data' AIRFLOW_CTX_TASK_ID='insert_battery_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-17T11:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-17T11:18:00+00:00'
[2024-07-17T11:24:16.071+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-17T11:24:16.082+0000] {logging_mixin.py:188} INFO - None
[2024-07-17T11:24:16.083+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-17T11:24:16.084+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 17, in insert_battery_data
    collect_data = get_battery()
                   ^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 11, in get_battery
    raise ValueError("No battery information available")
ValueError: No battery information available
[2024-07-17T11:24:16.306+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=computer_data, task_id=insert_battery_data_task, run_id=scheduled__2024-07-17T11:18:00+00:00, execution_date=20240717T111800, start_date=20240717T112414, end_date=20240717T112416
[2024-07-17T11:24:16.407+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task insert_battery_data_task (No battery information available; 121)
[2024-07-17T11:24:16.482+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-17T11:24:16.516+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-17T11:24:16.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
