[2024-07-16T10:58:24.079+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-16T10:58:24.915+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T10:55:00+00:00 [queued]>
[2024-07-16T10:58:24.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T10:55:00+00:00 [queued]>
[2024-07-16T10:58:24.975+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-16T10:58:25.130+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_battery_data_task> on 2024-07-16 10:55:00+00:00
[2024-07-16T10:58:25.259+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-16T10:58:25.289+0000] {standard_task_runner.py:63} INFO - Started process 130 to run task
[2024-07-16T10:58:25.310+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'computer_data', 'insert_battery_data_task', 'scheduled__2024-07-16T10:55:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/collect_to_postgre_dag.py', '--cfg-path', '/tmp/tmpcs_bonji']
[2024-07-16T10:58:25.369+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask insert_battery_data_task
[2024-07-16T10:58:26.022+0000] {task_command.py:426} INFO - Running <TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-16T10:55:00+00:00 [running]> on host 224660d77ef4
[2024-07-16T10:58:28.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='computer_data' AIRFLOW_CTX_TASK_ID='insert_battery_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T10:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-16T10:55:00+00:00'
[2024-07-16T10:58:28.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-16T10:58:28.502+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-16T10:58:28.504+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 19, in insert_battery_data
    data_to_insert = transform_battery(collect_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/battery.py", line 13, in transform_battery
    for data in battery_info:
TypeError: 'NoneType' object is not iterable
[2024-07-16T10:58:28.569+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=computer_data, task_id=insert_battery_data_task, run_id=scheduled__2024-07-16T10:55:00+00:00, execution_date=20240716T105500, start_date=20240716T105824, end_date=20240716T105828
[2024-07-16T10:58:28.627+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task insert_battery_data_task ('NoneType' object is not iterable; 130)
[2024-07-16T10:58:28.688+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-16T10:58:28.953+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-16T10:58:29.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
